const DOM_ATTR_PREFIX = "x-";
const DOM_ATTR_DELIMITER = ":";
const DOM_ATTR_HIDDEN = "hidden";

const DOM_PROP_VALUE = "value";
const DOM_PROP_TEXT = "textContent";
const DOM_PROP_HTML = "innerHTML";

const DIRECTIVE_KEY_INIT = 0;
const DIRECTIVE_KEY_RENDER = 1;

export {
    DOM_ATTR_PREFIX,
    DOM_ATTR_DELIMITER,
    DOM_ATTR_HIDDEN,

    DOM_PROP_VALUE,
    DOM_PROP_TEXT,
    DOM_PROP_HTML,

    DIRECTIVE_KEY_INIT,
    DIRECTIVE_KEY_RENDER
};
